services:
  - type: web
    name: aitutor
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y tesseract-ocr libtesseract-dev libleptonica-dev
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: '1'
